# A generic, single database configuration.

[alembic]
# Path to migration scripts
script_location = alembic

# Naming template for new migration files.
# %%(rev)s will be replaced by the --rev-id value (e.g. 001).
file_template = %%(rev)s_%%(slug)s

# Timezone for timestamps in migration files
# timezone =

# Max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command,
# regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a source .py file
# to be detected as revisions in the versions/ directory
# sourceless = false

# version_locations can be used to split the version directory into multiple
# If is defined here, %%(here)s will be replaced with the script_location
# version_locations = %%(here)s/bar:%(here)s/foo

# the output encoding used when revision files are written from
# script.py.mako
# output_encoding = utf-8

# logging configuration section
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
